name: GitHub actions
on: [push]
jobs:
  actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2.5.0
      - uses: iansu/codecov-action-node@v1.0.1
        with:
          flags: unittests 
      - run: npm install
      - run: npm run test
      

