name: GitHub actions
on: [push]
jobs:
  actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.5.0
        with:
          node-version: "14"
      - run: npm install
      - run: npm test
  unit-test:
    runs-on: ubuntu-latest
    name: publish unit tests results
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/test-reporter@v1
      if: success() || failure() 
      with:
          name: JEST Tests            
          path: junit.xml    
          reporter: jest-junit        
      

