name: GitHub actions
on: [push]
jobs:
  actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2.5.0
      - name: Install Dependencies
      - run: npm install
      - name: Run unit test with jest
      - run: npm run test
      

