name: GitHub actions
on: [push]
jobs:
  actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.5.0
        with:
          node-version: "14"
      - run: npm install
      - run: npm test
      - uses: dorny/test-reporter@v1.5.0
        if: success() || failure()
        with:
          name: JEST Tests
          path: reports/jest-*.xml
          reporter: jest-junit
      - uses: actions/setup-node@v2
        with:
            node-version: ${{ matrix.node-version }}
            registry-url: "https://registry.npmjs.org"
      - run: npm publish
        env:
            NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
